list = []
list.append(1)
print(list.count(2))
list.extend([2,3,5,4])
print(list)
print(list.index(5))
list.insert(2,6)
print(list)
print(list.pop(2))
print(list)
list.remove(5)
print(list)
list.reverse()
print(list)
list.sort()
print(list)


tuple = ('a','b','c')
list.insert(4,tuple)
print(list)
print(list[1:4])
print(tuple[2])
print(tuple[1:-1])